const REGISTER_USER = 'REGISTER_USER' as const;
const REGISTER_USER_SUCCESS  = 'REGISTER_USER_SUCCESS' as const;
const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR' as const;
const LOGIN_USER = 'LOGIN_USER' as const;
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS' as const;
const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR' as const;
const LOGOUT_USER = 'LOGOUT_USER' as const;
const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS' as const;
const LOGOUT_USER_ERROR  = 'LOGOUT_USER_ERROR' as const;
const REFRESH_TOKEN  = 'REFRESH_TOKEN' as const;
const REFRESH_TOKEN_SUCCESS  = 'REFRESH_TOKEN_SUCCESS' as const;
const REFRESH_TOKEN_ERROR  = 'REFRESH_TOKEN_ERROR' as const;
const RESET_PASSWORD  = 'RESET_PASSWORD' as const;
const RESET_PASSWORD_SUCCESS  = 'RESET_PASSWORD_SUCCESS' as const;
const RESET_PASSWORD_ERROR  = 'RESET_PASSWORD_ERROR' as const;
const UPDATE_PASSWORD = 'UPDATE_PASSWORD' as const;
const UPDATE_PASSWORD_ERROR  = 'UPDATE_PASSWORD_ERROR' as const;
const UPDATE_PASSWORD_SUCCESS  = 'UPDATE_PASSWORD_SUCCESS' as const;
const UPDATE_USER  = 'UPDATE_USER' as const;
const UPDATE_USER_ERROR  = 'UPDATE_USER_ERROR' as const;
const UPDATE_USER_SUCCESS  = 'UPDATE_USER_SUCCESS' as const;
const GET_USER = 'GET_USER' as const;
const GET_USER_ERROR  = 'GET_USER_ERROR' as const;
const GET_USER_SUCCESS  = 'GET_USER_SUCCESS' as const;

const ADD_ITEM = 'ADD_ITEM' as const;
const REMOVE_ITEM = 'REMOVE_ITEM' as const;
const INIT_NEW_CART = 'INIT_NEW_CART' as const;
const ADD_BUNS = 'ADD_BUNS' as const;
const REMOVE_BUNS = 'REMOVE_BUNS' as const;
const MOVE_ITEMS = 'MOVE_ITEMS' as const;

const SET_INGREDIENT = 'SET_INGREDIENT' as const;
const DELETE_INGREDIENT = 'DELETE_INGREDIENT' as const;
const INIT_INGREDIENT = 'INIT_INGREDIENT' as const;

const GET_INGREDIENTS = 'GET_INGREDIENTS' as const;
const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS' as const;
const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR' as const;

const GET_ORDER = 'GET_ORDER' as const;
const GET_ORDER_ERROR = 'GET_ORDER_ERROR' as const;
const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS' as const;

export const URL_WS = "wss://norma.nomoreparties.space/orders/all";

export {
    REGISTER_USER_SUCCESS,
    REGISTER_USER_ERROR,
    REGISTER_USER,
    LOGIN_USER_ERROR,
    LOGOUT_USER,
    LOGIN_USER_SUCCESS,
    LOGOUT_USER_ERROR,
    LOGOUT_USER_SUCCESS,
    LOGIN_USER,
    REFRESH_TOKEN_SUCCESS,
    REFRESH_TOKEN,
    REFRESH_TOKEN_ERROR,
    RESET_PASSWORD,
    RESET_PASSWORD_SUCCESS,
    RESET_PASSWORD_ERROR,
    UPDATE_USER_ERROR,
    UPDATE_USER_SUCCESS,
    UPDATE_USER,
    UPDATE_PASSWORD,
    UPDATE_PASSWORD_ERROR,
    UPDATE_PASSWORD_SUCCESS,
    GET_USER_SUCCESS,
    GET_USER_ERROR,
    GET_USER,
    ADD_ITEM,
    REMOVE_ITEM,
    INIT_NEW_CART,
    ADD_BUNS,
    REMOVE_BUNS,
    MOVE_ITEMS,
    SET_INGREDIENT,
    DELETE_INGREDIENT,
    INIT_INGREDIENT,
    GET_INGREDIENTS,
    GET_INGREDIENTS_ERROR,
    GET_INGREDIENTS_SUCCESS,
    GET_ORDER_SUCCESS,
    GET_ORDER,
    GET_ORDER_ERROR
}